
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 20 16:21:26 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 11;
  public static final int INCREMENT = 29;
  public static final int CONST = 5;
  public static final int ASSIGNMENT = 28;
  public static final int MULASSIGN = 21;
  public static final int NOT_EQUAL = 46;
  public static final int GREATER = 41;
  public static final int CONTINUE = 39;
  public static final int NUM_CONST = 10;
  public static final int FOR = 37;
  public static final int MINUS = 15;
  public static final int DECREMENT = 30;
  public static final int SEMICOLON = 31;
  public static final int AND = 12;
  public static final int DIVASSIGN = 22;
  public static final int OR = 13;
  public static final int COMMA = 32;
  public static final int LEFT_BRACE = 24;
  public static final int RIGHT_PARENTHESIS = 34;
  public static final int LESSER = 43;
  public static final int PLUS = 14;
  public static final int IF = 35;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int EQUAL = 42;
  public static final int GREATER_EQUAL = 44;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 18;
  public static final int RIGHT_BRACE = 25;
  public static final int BREAK = 38;
  public static final int IDENT = 9;
  public static final int VOID = 6;
  public static final int MODASSIGN = 23;
  public static final int ADDASSIGN = 19;
  public static final int SUBASSIGN = 20;
  public static final int LEFT_SQUARE = 26;
  public static final int ELSE = 36;
  public static final int READ = 4;
  public static final int LESSER_EQUAL = 45;
  public static final int RIGHT_SQUARE = 27;
  public static final int BOOL_CONST = 8;
  public static final int DIVISION = 17;
  public static final int MULTIPLICATION = 16;
  public static final int PRINT = 3;
  public static final int LEFT_PARENTHESIS = 33;
}

